#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "xparameters.h"

#define APP_CUSTOM_UART_BASE XPAR_UART_0_S00_AXI_BASEADDR

#define APP_STARTUP_PATTERN      0x00A5U
#define APP_WAIT_PATTERN_INITIAL 0x00F0U
#define APP_WAIT_PATTERN_TOGGLE  0x000FU
#define APP_STARTUP_DELAY_US     500000U
#define APP_WAIT_INTERVAL_US     200000U

#endif
